---
name: "pipeline-components-stylelint"
description: "stylelint by Pipeline Components"
author: "Robbert Müller <spam.me@grols.ch>"
branding:
  icon: "flag"
  color: "green"
inputs:
  directory:
    description: "Directory to lint"
    required: false
    default: "**/*.css"
  options:
    description: "Additional options"
    required: false
    default: "--color"
runs:
  using: "docker"
  image: docker://pipelinecomponents/stylelint
  args:
    - stylelint
    - "${{ inputs.options }}"
    - "${{ inputs.directory }}"
